name: wavvv

packages:
  - apps/*
  - packages/*
sdkPath: .fvm/flutter_sdk
scripts:
  build_all:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: build_runner build all modules.

  build_auth:
    run: melos exec --scope=authentication -- fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: Build runner for authentication package only

  build_core:
    run: melos exec --scope=core -- fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: Build runner for core package only
  build_notify:
    run: melos exec --scope=notification -- fvm flutter pub run build_runner build --delete-conflicting-outputs
    description: Build runner for notification package only
