// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa2suLLiuvDmkTisxPg1oxxYojKx40zhw',
    appId: '1:353946571533:web:f540d00c325bb1d272d644',
    messagingSenderId: '353946571533',
    projectId: 'tcareer-4fa7d',
    authDomain: 'tcareer-4fa7d.firebaseapp.com',
    databaseURL:
        'https://tcareer-4fa7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcareer-4fa7d.appspot.com',
    measurementId: 'G-JRVZ98QJCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFj0CXj0QXMpM1da5Yvs4vo48UniEOr8k',
    appId: '1:353946571533:android:0c31a6ed7b3c5b7d72d644',
    messagingSenderId: '353946571533',
    projectId: 'tcareer-4fa7d',
    databaseURL:
        'https://tcareer-4fa7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcareer-4fa7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCulh18okOXCMgniairGxVDmhviE-TvabA',
    appId: '1:353946571533:ios:b2ad53c0bad8edb172d644',
    messagingSenderId: '353946571533',
    projectId: 'tcareer-4fa7d',
    databaseURL:
        'https://tcareer-4fa7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcareer-4fa7d.appspot.com',
    androidClientId:
        '353946571533-aeevc7u3rh5l91jueeepfm4q6btgts52.apps.googleusercontent.com',
    iosClientId:
        '353946571533-q47i75ail4f4p2bq01k0gj331rae5h29.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcareer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCulh18okOXCMgniairGxVDmhviE-TvabA',
    appId: '1:353946571533:ios:b2ad53c0bad8edb172d644',
    messagingSenderId: '353946571533',
    projectId: 'tcareer-4fa7d',
    databaseURL:
        'https://tcareer-4fa7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcareer-4fa7d.appspot.com',
    androidClientId:
        '353946571533-aeevc7u3rh5l91jueeepfm4q6btgts52.apps.googleusercontent.com',
    iosClientId:
        '353946571533-q47i75ail4f4p2bq01k0gj331rae5h29.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTcareer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa2suLLiuvDmkTisxPg1oxxYojKx40zhw',
    appId: '1:353946571533:web:6fba8fdc1f6cbe4c72d644',
    messagingSenderId: '353946571533',
    projectId: 'tcareer-4fa7d',
    authDomain: 'tcareer-4fa7d.firebaseapp.com',
    databaseURL:
        'https://tcareer-4fa7d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tcareer-4fa7d.appspot.com',
    measurementId: 'G-DYV36E6MF5',
  );
}
